import mongoose from "mongoose";

const studentSchema = new mongoose.Schema(
  {
    name: { type: String, required: true },
    class: { type: String, required: true },
    rollNumber: { type: String, required: true, unique: true },
    email: { type: String, required: true },
    phone: { type: String, required: true },
    address: { type: String },
    school: { type: String },
    joiningDate: { type: Date },
    // Credentials - generated by teacher
    passwordHash: { type: String }, // Hashed password (generated randomly)
    plainPassword: { type: String }, // Store plain password temporarily for display (cleared after first login)
    credentialsGenerated: { type: Boolean, default: false },
    isFirstLogin: { type: Boolean, default: true }, // Track if student needs to change password
    teacherId: { type: String, required: true }, // Teacher ID who created the student (e.g., "Ajay123")

    // Points and Progress
    points: { type: Number, default: 0 }, // Eco points for environmental activities
    gamePoints: { type: Number, default: 0 }, // Game points for level progression
    todayPoints: { type: Number, default: 0 },
    lastPointsDate: { type: Date },
    streak: { type: Number, default: 0 },
    level: { type: Number, default: 1 },
    currentXP: { type: Number, default: 0 },
    nextLevelXP: { type: Number, default: 100 },
    badges: [
      {
        badgeId: { type: String },
        name: { type: String },
        description: { type: String },
        level: { type: Number },
        icon: { type: String },
        rarity: { type: String },
        earnedAt: { type: Date, default: Date.now },
      },
    ],
    
    // Achievements tracking
    achievements: [
      {
        achievementId: { type: String },
        title: { type: String },
        currentProgress: { type: Number, default: 0 },
        targetValue: { type: Number },
        completed: { type: Boolean, default: false },
        completedAt: { type: Date },
      },
    ],
    
    hoursLearned: { type: Number, default: 0 },

    // Daily challenges - array format
    dailyChallenges: [
      {
        id: { type: String },
        type: { type: String },
        title: { type: String },
        description: { type: String },
        xpReward: { type: Number },
        completed: { type: Boolean, default: false },
        completedAt: { type: Date },
      },
    ],
    dailyChallengeCompleted: { type: Boolean, default: false },

    // Watched videos tracking
    watchedVideos: [
      {
        syllabusId: { type: mongoose.Schema.Types.ObjectId, ref: "Syllabus" },
        watchedAt: { type: Date, default: Date.now },
        pointsEarned: { type: Number, default: 0 },
      },
    ],

    // Quiz scores / Completed Quizzes
    quizScores: [
      {
        syllabusId: { type: mongoose.Schema.Types.ObjectId, ref: "Syllabus" },
        score: { type: Number },
        completedAt: { type: Date, default: Date.now },
      },
    ],

    // Completed quizzes with points tracking
    completedQuizzes: [
      {
        syllabusId: { type: mongoose.Schema.Types.ObjectId, ref: "Syllabus" },
        quizTitle: { type: String },
        score: { type: Number },
        pointsAwarded: { type: Number, default: 0 },
        completedAt: { type: Date, default: Date.now },
      },
    ],

    // Games tracking
    gamesPlayed: [
      {
        gameId: { type: String },
        gameName: { type: String },
        pointsEarned: { type: Number, default: 0 },
        playedAt: { type: Date, default: Date.now },
      },
    ],

    // Currency and Rewards
    coins: { type: Number, default: 0 },
    gifts: [
      {
        giftId: { type: String },
        name: { type: String },
        description: { type: String },
        receivedAt: { type: Date, default: Date.now },
      },
    ],
    cards: [
      {
        cardId: { type: String },
        name: { type: String },
        rarity: { type: String }, // common, rare, epic, legendary
        receivedAt: { type: Date, default: Date.now },
      },
    ],

    // Level up rewards tracking
    levelUpRewards: [
      {
        level: { type: Number },
        rewardType: { type: String }, // 'coins', 'gift', 'card'
        rewardValue: { type: mongoose.Schema.Types.Mixed },
        claimedAt: { type: Date, default: Date.now },
      },
    ],

    // Rewards store redemptions
    redemptions: [
      {
        itemId: { type: String, required: true },
        itemName: { type: String, required: true },
        category: { type: String },
        coinsSpent: { type: Number, required: true },
        redeemedAt: { type: Date, default: Date.now },
      },
    ],

    createdAt: { type: Date, default: Date.now },
  },
  {
    timestamps: true,
  }
);

const Student = mongoose.model("Student", studentSchema);

export default Student;
